// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewReplyInfo = "review_reply_info"

// ReviewReplyInfo mapped from table <review_reply_info>
type ReviewReplyInfo struct {
	ID        int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateBy  string     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy  string     `gorm:"column:update_by;not null" json:"update_by"`
	CreateAt  time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt  time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	DeleteAt  *time.Time `gorm:"column:delete_at" json:"delete_at"`
	Version   int32      `gorm:"column:version;not null" json:"version"`
	ReplyID   int64      `gorm:"column:reply_id;not null;comment:id" json:"reply_id"`   // id
	ReviewID  int64      `gorm:"column:review_id;not null;comment:id" json:"review_id"` // id
	StoreID   int64      `gorm:"column:store_id;not null;comment:id" json:"store_id"`   // id
	Content   string     `gorm:"column:content;not null" json:"content"`
	PicInfo   string     `gorm:"column:pic_info;not null" json:"pic_info"`
	VideoInfo string     `gorm:"column:video_info;not null" json:"video_info"`
	ExtJSON   string     `gorm:"column:ext_json;not null" json:"ext_json"`
	CtrlJSON  string     `gorm:"column:ctrl_json;not null" json:"ctrl_json"`
}

// TableName ReviewReplyInfo's table name
func (*ReviewReplyInfo) TableName() string {
	return TableNameReviewReplyInfo
}
