// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReviewAppealInfo = "review_appeal_info"

// ReviewAppealInfo mapped from table <review_appeal_info>
type ReviewAppealInfo struct {
	ID       int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateBy string     `gorm:"column:create_by;not null" json:"create_by"`
	UpdateBy string     `gorm:"column:update_by;not null" json:"update_by"`
	CreateAt time.Time  `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time  `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	DeleteAt *time.Time `gorm:"column:delete_at" json:"delete_at"`
	Version  int32      `gorm:"column:version;not null" json:"version"`
	AppealID int64      `gorm:"column:appeal_id;not null;comment:id" json:"appeal_id"` // id
	ReviewID int64      `gorm:"column:review_id;not null;comment:id" json:"review_id"` // id
	StoreID  int64      `gorm:"column:store_id;not null;comment:id" json:"store_id"`   // id
	/*
		:102030

	*/
	Status    int32  `gorm:"column:status;not null;default:10;comment::102030\n" json:"status"`
	Reason    string `gorm:"column:reason;not null" json:"reason"`
	Content   string `gorm:"column:content;not null" json:"content"`
	PicInfo   string `gorm:"column:pic_info;not null" json:"pic_info"`
	VideoInfo string `gorm:"column:video_info;not null" json:"video_info"`
	OpRemarks string `gorm:"column:op_remarks;not null" json:"op_remarks"`
	OpUser    string `gorm:"column:op_user;not null" json:"op_user"`
	ExtJSON   string `gorm:"column:ext_json;not null" json:"ext_json"`
	CtrlJSON  string `gorm:"column:ctrl_json;not null" json:"ctrl_json"`
}

// TableName ReviewAppealInfo's table name
func (*ReviewAppealInfo) TableName() string {
	return TableNameReviewAppealInfo
}
